.PHONY: run go python nodejs

run: go python nodejs

go:
	@echo "=== Go ==="
	@cd skeleton/go && go run main.go

python:
	@echo "=== Python ==="
	@cd skeleton/python && python3 main.py

nodejs:
	@echo "=== Node.js ==="
	@cd skeleton/nodejs && node index.js
